### ISSUE TITLE
How to use the prediction service?

### ISSUE THREAD

**Issue by tienduccao** [heartexlabs/label-studio-transformers#4] opened 2020-06-23 07:14 UTC
Hi, thanks for this great tool.
However I couldn't find a detailed instruction of using the prediction service both here and https://github.com/heartexlabs/label-studio/blob/master/docs/source/guide/tasks.md.
I'd like to generate NER annotations after training my model, select the uncertain predictions, and then continue labeling.
Thanks in advance.

**Comment by makseq** [comment] 2020-06-24 13:57
Hi, the task json has the field "predictions": []. They are the very similar to completions. 
You have three ways: 
1 import tasks with ready predictions 
2 change <your_project>/tasks.json manually and add/rewrite your prediction
3 add ml backend with your model: https://labelstud.io/guide/ml.html

**Comment by tienduccao** [comment] 2020-06-24 14:03
Hi @makseq  I did try the 3rd approach with ML backend but it didn't work.
I'll add the details of my setup and let you know soon.

**Comment by tienduccao** [comment] 2020-06-26 05:54
I tried to label for an NER task.

__label-studio-ml init my-ml-backend --script models/ner.py
cp models/utils.py my-ml-backend/utils.py
label-studio-ml start my-ml-backend 
label-studio start my-annotation-project --init --ml-backend http://localhost:9090__

Here is the error log
```
Traceback (most recent call last):                               
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app                                                                                                                                               
    response = self.full_dispatch_request()                                                                                         
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)                           
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)                                                                                                                                                                                                                                      File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise                                                                                                                                              
    raise value                                   
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()                                                                                                    
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request                                                                                                                                       
    return self.view_functions[rule.endpoint](**req.view_args)                                                                      
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/api.py", line 29, in _predict                                                                                                                                       
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)                                                                                                                                                              
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/model.py", line 264, in predict                                                                                                                                     
    predictions = m.model.predict(tasks, **kwargs)                                                                                                                                                                                                                      
  File "PROJECT/label-studio-transformers/my-ml-backend/ner.py", line 368, in predict                                                                                                                                                                          
    predict_set = SpanLabeledTextDataset(texts, tokenizer=self._tokenizer, **self._dataset_params_dict)                                                                                                                                                                 
AttributeError: 'TransformersBasedTagger' object has no attribute '_tokenizer'                                  
```

**Comment by tienduccao** [comment] 2020-06-26 05:54
When I tried the text classification tasks, there's a similar error
```
Traceback (most recent call last):
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/api.py", line 29, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/model.py", line 264, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "PROJECT/label-studio-transformers/my-ml-backend/bert_classifier.py", line 80, in predict
    predict_dataloader = prepare_texts(texts, self.tokenizer, self.maxlen, SequentialSampler, self.batch_size)
AttributeError: 'BertClassifier' object has no attribute 'tokenizer
```

**Comment by katreparitosh** [comment] 2020-09-14 09:19
@tienduccao Even I am facing a similar issue with Tokenizer. Did you find any solution?

**Comment by fromnorthpole** [comment] 2020-09-16 10:24
@tienduccao @katreparitosh have you tried to train the model before (by pressing **Start Training** button on the **Model** page)? Does the error persist then you label the tasks afterward?

**Comment by katreparitosh** [comment] 2020-09-16 18:42
@fromnorthpole I guess I tried. But I recieved "No Completions Found" error when I pushed Start Training without any labelled tasks.

**Comment by Pradip2205** [comment] 2021-01-20 05:02
> When I tried the text classification tasks, there's a similar error
> 
> ```
> Traceback (most recent call last):
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/api.py", line 29, in _predict
>     predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
>   File "PROJECT/label-studio-transformers/.env/lib/python3.8/site-packages/label_studio/ml/model.py", line 264, in predict
>     predictions = m.model.predict(tasks, **kwargs)
>   File "PROJECT/label-studio-transformers/my-ml-backend/bert_classifier.py", line 80, in predict
>     predict_dataloader = prepare_texts(texts, self.tokenizer, self.maxlen, SequentialSampler, self.batch_size)
> AttributeError: 'BertClassifier' object has no attribute 'tokenizer
> ```

**Comment by Pradip2205** [comment] 2021-01-20 05:03
Did you find any solution to this error ?

**Comment by niklub** [comment] 2021-02-08 15:00
> @fromnorthpole I guess I tried. But I recieved "No Completions Found" error when I pushed Start Training without any labelled tasks.

Sorry for the late response. Did you encounter any error while annotating data besides this error log? We definitely should improve error handling, but currently the problem is that you can't get preannotations until your model is ready (and this unshapely traceback is just an indicator of this fact). So you need first to label some data, then press start training, wait until the model is trained and eventually you should get preannotations without any errors in console logs.
Let me know if you need any clarifications on that.

**Comment by niklub** [comment] 2021-03-30 14:05
Hi,
Though this was just annoying log message, not an actual bug, it has been fixed in the latest master. Please reopen the issue if this problem remains on your side.

**Closed as completed by niklub** 2021-03-30 14:05 UTC
